# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/STOVAG/Desktop/cpu_vga_ip_test/cpu_vga_top/cpu/cpu.srcs/sources_1/ip/vga_controller_0/vga_controller_0.xci
# IP: The module: 'vga_controller_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/STOVAG/Desktop/cpu_vga_ip_test/cpu_vga_top/cpu/cpu.srcs/sources_1/ip/vga_controller_0/src/clk_wiz_ip/clk_wiz_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_ip || ORIG_REF_NAME==clk_wiz_ip} -quiet] -quiet

# XDC: c:/Users/STOVAG/Desktop/cpu_vga_ip_test/cpu_vga_top/cpu/cpu.srcs/sources_1/ip/vga_controller_0/src/clk_wiz_ip/clk_wiz_ip_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_ip || ORIG_REF_NAME==clk_wiz_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/STOVAG/Desktop/cpu_vga_ip_test/cpu_vga_top/cpu/cpu.srcs/sources_1/ip/vga_controller_0/src/clk_wiz_ip/clk_wiz_ip.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_ip || ORIG_REF_NAME==clk_wiz_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/STOVAG/Desktop/cpu_vga_ip_test/cpu_vga_top/cpu/cpu.srcs/sources_1/ip/vga_controller_0/src/clk_wiz_ip/clk_wiz_ip_ooc.xdc

# IP: c:/Users/STOVAG/Desktop/cpu_vga_ip_test/cpu_vga_top/cpu/cpu.srcs/sources_1/ip/vga_controller_0/vga_controller_0.xci
# IP: The module: 'vga_controller_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/STOVAG/Desktop/cpu_vga_ip_test/cpu_vga_top/cpu/cpu.srcs/sources_1/ip/vga_controller_0/src/clk_wiz_ip/clk_wiz_ip.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_ip || ORIG_REF_NAME==clk_wiz_ip} -quiet] -quiet

# XDC: c:/Users/STOVAG/Desktop/cpu_vga_ip_test/cpu_vga_top/cpu/cpu.srcs/sources_1/ip/vga_controller_0/src/clk_wiz_ip/clk_wiz_ip_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_ip || ORIG_REF_NAME==clk_wiz_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/STOVAG/Desktop/cpu_vga_ip_test/cpu_vga_top/cpu/cpu.srcs/sources_1/ip/vga_controller_0/src/clk_wiz_ip/clk_wiz_ip.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_ip || ORIG_REF_NAME==clk_wiz_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/STOVAG/Desktop/cpu_vga_ip_test/cpu_vga_top/cpu/cpu.srcs/sources_1/ip/vga_controller_0/src/clk_wiz_ip/clk_wiz_ip_ooc.xdc
